input {
  file {
    path => "/var/log/app/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  mutate {
    add_field => {
      "project" => "ft_transcendance"
      "env" => "dev"
    }
  }
}

output {
  elastic {
    hosts => ["http://elastic:9200"]
    index => "ft-transcendance-logs-%{+YYYY.MM.dd}"
    ilm_enabled => true
    ilm_policy => "logs-retention-7d"
  }

  stdout { codec => rubydebug }
}
