input {
  # file {
  #   path => "/var/log/app/*.log"
  #   start_position => "beginning"
  #   sincedb_path => "/dev/null"
  # }
  gelf {
    port => 12201
  }
}

filter {

  mutate {
    gsub => [
      # \\\\\" = “je cherche le texte \"” pour échapper à l'échappement logstash
      # " = je remplace par un guillemet normal
      "message", "\\\\\"", "\""  
    ]
  }
  json {
    source => "message"
    target => "log"
    tag_on_failure => ["json_parse_failed"]
    # skip_on_invalid_json => true
  }
  
  mutate {
    add_field => {
      "project" => "ft_transcendance"
      "env" => "dev"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "ft-transcendance-logs-%{+YYYY.MM.dd}"
    ilm_enabled => true
    ilm_policy => "logs-retention-7d"
  }

  stdout { codec => rubydebug }
}
